### ISSUE TITLE
Unsecure cookie

### ISSUE THREAD

**Issue by alexander-binas** [LoopFiftyFour/PHP-Connector#4]
Now this is not so dangerous when this cookie had the user's IP address.

We make Loop54User cookie as setcookie($key, $value, $time); 

In this case, this cookie can be read in an unprotected http connection and can be read/modified using  JavaScript code.

See
https://www.owasp.org/index.php/HttpOnly
https://www.owasp.org/index.php/SecureFlag

**Comment by joelwkall** [comment]
I agree, and thanks for notifying us! 

However, we don't want to limit the usage of the cookie for several reasons:

- The Loop54 implementation can be mixed, so that you use a javascript component in the frontend (for instance for autocomplete) and we want it to be able to read the cookie.
- We do not want to force https for legacy reasons. 

Both of the above can be achieved with HttpOnly and SecureFlag given enough effort, but since the data in this cookie is not very sensitive (it's just a random ID), I don't think we will be spending time on that.
